### ISSUE TITLE
Funktioniert nicht mehr :(

### ISSUE THREAD

**Issue by gamersi** [chrba/jerman#1]

**Comment by gamersi** [comment]
[info] welcome to sbt 1.9.9 (N/A Java 17.0.11)
[info] loading settings for project jerman_test-build from plugins.sbt ...
[info] loading project definition from /home/simon/IdeaProjects/jerman_test/project
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		de.jerman:jerman:1.0.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading de.jerman:jerman;sbtVersion=1.0;scalaVersion=2.12:1.0.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/de/jerman/jerman_2.12_1.0/1.0.1/jerman-1.0.1.pom
[error]   not found: /home/simon/.ivy2/localde.jerman/jerman/scala_2.12/sbt_1.0/1.0.1/ivys/ivy.xml
[error]   not found: https://dl.bintray.com/chrba/maven/de/jerman/jerman_2.12_1.0/1.0.1/jerman-1.0.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/de.jerman/jerman/scala_2.12/sbt_1.0/1.0.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/de.jerman/jerman/scala_2.12/sbt_1.0/1.0.1/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading de.jerman:jerman;sbtVersion=1.0;scalaVersion=2.12:1.0.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/de/jerman/jerman_2.12_1.0/1.0.1/jerman-1.0.1.pom
[error]   not found: /home/simon/.ivy2/localde.jerman/jerman/scala_2.12/sbt_1.0/1.0.1/ivys/ivy.xml
[error]   not found: https://dl.bintray.com/chrba/maven/de/jerman/jerman_2.12_1.0/1.0.1/jerman-1.0.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/de.jerman/jerman/scala_2.12/sbt_1.0/1.0.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/de.jerman/jerman/scala_2.12/sbt_1.0/1.0.1/ivys/ivy.xml

**Comment by gamersi** [comment]
ich wollte das erste Projekt in Jerman machen aber jetzt kann ich das nicht mehr :(

**Comment by 137-Trimethylxanthin** [comment]
## fuck man
# 🚬 😞

**Comment by critiqalfish** [comment]
count stirk 1.6 game:

for (float stirk = 0; stirk < 1.6; stirk += 0.1) {
        // count stirk
}
